import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { vanillaExtractPlugin } from "@vanilla-extract/esbuild-plugin";
import fs from "fs"; // Importe o módulo de sistema de arquivos

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

/**
 * Plugin customizado para forçar o nome styles.css
 */
const fixStylesName = {
	name: 'fix-styles-name',
	setup(build) {
		build.onEnd(() => {
			if (fs.existsSync("main.css")) {
				// Remove o styles.css antigo se existir para evitar erro no rename
				if (fs.existsSync("styles.css")) {
					fs.unlinkSync("styles.css");
				}
				fs.renameSync("main.css", "styles.css");
				console.log("✅ CSS extraído e renomeado para styles.css");
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	plugins: [
		vanillaExtractPlugin({
			identifiers: "short", // Mantém o nome curto que você configurou
		}),
		fixStylesName // Adicione o nosso plugin aqui
	],
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}