import { GLOBAL_COLORS, theme } from "./global.css";


export const defaultTheme: theme = {
    name: "",
    degre: "180deg",
    defaultColor: GLOBAL_COLORS.default.color,
    textPrimaryColor: GLOBAL_COLORS.default.black,
    textSecondaryColor: GLOBAL_COLORS.default.white,
    gradientEndColor: GLOBAL_COLORS.gradientEnd.color,
    markerDefaultColor: GLOBAL_COLORS.default.white,
    mutedColor: GLOBAL_COLORS.muted.color,
    lighterColor: GLOBAL_COLORS.lighter.color,
    darkerColor: GLOBAL_COLORS.darker.color,
    darkestColor: GLOBAL_COLORS.darkest.color,
    transparentColor: GLOBAL_COLORS.transparent.color,
    highlightColor: GLOBAL_COLORS.highlight.yellow,
    contrastColor: GLOBAL_COLORS.contrast.color,
    glassColor: GLOBAL_COLORS.glass.color,
    linkExternalColor: GLOBAL_COLORS.default.blue,
    linkInternalColor: GLOBAL_COLORS.default.blue,
};

export const themes: theme[] = [
    {
        name: "red",
        defaultColor: GLOBAL_COLORS.default.red,
        textPrimaryColor: GLOBAL_COLORS.default.white,
        textSecondaryColor: GLOBAL_COLORS.default.white,
        gradientEndColor: GLOBAL_COLORS.gradientEnd.red,
        markerDefaultColor: GLOBAL_COLORS.darker.red,
        mutedColor: GLOBAL_COLORS.muted.red,
        lighterColor: GLOBAL_COLORS.lighter.red,
        darkerColor: GLOBAL_COLORS.darker.red,
        darkestColor: GLOBAL_COLORS.darkest.red,
        transparentColor: GLOBAL_COLORS.transparent.red,
        highlightColor: GLOBAL_COLORS.highlight.red,
        contrastColor: GLOBAL_COLORS.contrast.red,
        glassColor: GLOBAL_COLORS.glass.red,
    },
    {
        name: "green",
        defaultColor: GLOBAL_COLORS.default.green,
        textPrimaryColor: GLOBAL_COLORS.default.white,
        textSecondaryColor: GLOBAL_COLORS.default.white,
        gradientEndColor: GLOBAL_COLORS.gradientEnd.green,
        markerDefaultColor: GLOBAL_COLORS.darker.green,
        mutedColor: GLOBAL_COLORS.muted.green,
        lighterColor: GLOBAL_COLORS.lighter.green,
        darkerColor: GLOBAL_COLORS.darker.green,
        darkestColor: GLOBAL_COLORS.darkest.green,
        transparentColor: GLOBAL_COLORS.transparent.green,
        highlightColor: GLOBAL_COLORS.highlight.green,
        contrastColor: GLOBAL_COLORS.contrast.green,
        glassColor: GLOBAL_COLORS.glass.green
    },
    {
        name: "blue",
        defaultColor: GLOBAL_COLORS.default.blue,
        textPrimaryColor: GLOBAL_COLORS.default.white,
        textSecondaryColor: GLOBAL_COLORS.default.white,
        gradientEndColor: GLOBAL_COLORS.gradientEnd.blue,
        markerDefaultColor: GLOBAL_COLORS.darker.blue,
        linkExternalColor: GLOBAL_COLORS.default.yellow,
        linkInternalColor: GLOBAL_COLORS.default.yellow,
        mutedColor: GLOBAL_COLORS.muted.blue,
        lighterColor: GLOBAL_COLORS.lighter.blue,
        darkerColor: GLOBAL_COLORS.darker.blue,
        darkestColor: GLOBAL_COLORS.darkest.blue,
        transparentColor: GLOBAL_COLORS.transparent.blue,
        highlightColor: GLOBAL_COLORS.highlight.blue,
        contrastColor: GLOBAL_COLORS.contrast.blue,
        glassColor: GLOBAL_COLORS.glass.blue
    },
    {
        name: "yellow",
        defaultColor: GLOBAL_COLORS.default.yellow,
        textPrimaryColor: GLOBAL_COLORS.default.white,
        textSecondaryColor: GLOBAL_COLORS.default.white,
        gradientEndColor: GLOBAL_COLORS.gradientEnd.yellow,
        markerDefaultColor: GLOBAL_COLORS.darker.yellow,
        mutedColor: GLOBAL_COLORS.muted.yellow,
        lighterColor: GLOBAL_COLORS.lighter.yellow,
        darkerColor: GLOBAL_COLORS.darker.yellow,
        darkestColor: GLOBAL_COLORS.darkest.yellow,
        transparentColor: GLOBAL_COLORS.transparent.yellow,
        highlightColor: GLOBAL_COLORS.highlight.yellow,
        contrastColor: GLOBAL_COLORS.contrast.yellow,
        glassColor: GLOBAL_COLORS.glass.yellow
    },
    {
        name: "purple",
        defaultColor: GLOBAL_COLORS.default.purple,
        textPrimaryColor: GLOBAL_COLORS.default.white,
        textSecondaryColor: GLOBAL_COLORS.default.white,
        gradientEndColor: GLOBAL_COLORS.gradientEnd.purple,
        markerDefaultColor: GLOBAL_COLORS.darker.purple,
        mutedColor: GLOBAL_COLORS.muted.purple,
        lighterColor: GLOBAL_COLORS.lighter.purple,
        darkerColor: GLOBAL_COLORS.darker.purple,
        darkestColor: GLOBAL_COLORS.darkest.purple,
        transparentColor: GLOBAL_COLORS.transparent.purple,
        highlightColor: GLOBAL_COLORS.highlight.purple,
        contrastColor: GLOBAL_COLORS.contrast.purple,
        glassColor: GLOBAL_COLORS.glass.purple
    },
    {
        name: "orange",
        defaultColor: GLOBAL_COLORS.default.orange,
        textPrimaryColor: GLOBAL_COLORS.default.white,
        textSecondaryColor: GLOBAL_COLORS.default.white,
        gradientEndColor: GLOBAL_COLORS.gradientEnd.orange,
        markerDefaultColor: GLOBAL_COLORS.darker.orange,
        mutedColor: GLOBAL_COLORS.muted.orange,
        lighterColor: GLOBAL_COLORS.lighter.orange,
        darkerColor: GLOBAL_COLORS.darker.orange,
        darkestColor: GLOBAL_COLORS.darkest.orange,
        transparentColor: GLOBAL_COLORS.transparent.orange,
        highlightColor: GLOBAL_COLORS.highlight.orange,
        contrastColor: GLOBAL_COLORS.contrast.orange,
        glassColor: GLOBAL_COLORS.glass.orange
    },
    {
        name: "cyan",
        defaultColor: GLOBAL_COLORS.default.cyan,
        textPrimaryColor: GLOBAL_COLORS.default.white,
        textSecondaryColor: GLOBAL_COLORS.default.white,
        gradientEndColor: GLOBAL_COLORS.gradientEnd.cyan,
        markerDefaultColor: GLOBAL_COLORS.darker.cyan,
        mutedColor: GLOBAL_COLORS.muted.cyan,
        lighterColor: GLOBAL_COLORS.lighter.cyan,
        darkerColor: GLOBAL_COLORS.darker.cyan,
        darkestColor: GLOBAL_COLORS.darkest.cyan,
        transparentColor: GLOBAL_COLORS.transparent.cyan,
        highlightColor: GLOBAL_COLORS.highlight.cyan,
        contrastColor: GLOBAL_COLORS.contrast.cyan,
        glassColor: GLOBAL_COLORS.glass.cyan
    },
    {
        name: "pink",
        defaultColor: GLOBAL_COLORS.default.pink,
        textPrimaryColor: GLOBAL_COLORS.default.white,
        textSecondaryColor: GLOBAL_COLORS.default.white,
        gradientEndColor: GLOBAL_COLORS.gradientEnd.pink,
        markerDefaultColor: GLOBAL_COLORS.darker.pink,
        mutedColor: GLOBAL_COLORS.muted.pink,
        lighterColor: GLOBAL_COLORS.lighter.pink,
        darkerColor: GLOBAL_COLORS.darker.pink,
        darkestColor: GLOBAL_COLORS.darkest.pink,
        transparentColor: GLOBAL_COLORS.transparent.pink,
        highlightColor: GLOBAL_COLORS.highlight.pink,
        contrastColor: GLOBAL_COLORS.contrast.pink,
        glassColor: GLOBAL_COLORS.glass.pink
    },
    {
        name: "gray",
        defaultColor: GLOBAL_COLORS.default.gray,
        textPrimaryColor: GLOBAL_COLORS.default.white,
        textSecondaryColor: GLOBAL_COLORS.default.white,
        gradientEndColor: GLOBAL_COLORS.gradientEnd.gray,
        markerDefaultColor: GLOBAL_COLORS.darker.gray,
        mutedColor: GLOBAL_COLORS.muted.gray,
        lighterColor: GLOBAL_COLORS.lighter.gray,
        darkerColor: GLOBAL_COLORS.darker.gray,
        darkestColor: GLOBAL_COLORS.darkest.gray,
        transparentColor: GLOBAL_COLORS.transparent.gray,
        highlightColor: GLOBAL_COLORS.highlight.gray,
        contrastColor: GLOBAL_COLORS.contrast.gray,
        glassColor: GLOBAL_COLORS.glass.gray
    },
    {
        name: "white",
        defaultColor: GLOBAL_COLORS.default.white,
        textPrimaryColor: GLOBAL_COLORS.default.black,
        textSecondaryColor: GLOBAL_COLORS.default.white,
        gradientEndColor: GLOBAL_COLORS.gradientEnd.color,
        markerDefaultColor: GLOBAL_COLORS.darker.color,
        mutedColor: GLOBAL_COLORS.muted.color,
        lighterColor: GLOBAL_COLORS.lighter.color,
        darkerColor: GLOBAL_COLORS.darker.color,
        darkestColor: GLOBAL_COLORS.darkest.color,
        transparentColor: GLOBAL_COLORS.transparent.color,
        highlightColor: GLOBAL_COLORS.highlight.color,
        contrastColor: GLOBAL_COLORS.contrast.color,
        glassColor: GLOBAL_COLORS.glass.color
    },
    {
        name: "black",
        defaultColor: GLOBAL_COLORS.default.black,
        textPrimaryColor: GLOBAL_COLORS.default.white,
        textSecondaryColor: GLOBAL_COLORS.default.white,
        gradientEndColor: GLOBAL_COLORS.gradientEnd.color,
        markerDefaultColor: GLOBAL_COLORS.darker.color,
        mutedColor: GLOBAL_COLORS.muted.color,
        lighterColor: GLOBAL_COLORS.lighter.color,
        darkerColor: GLOBAL_COLORS.darker.color,
        darkestColor: GLOBAL_COLORS.darkest.color,
        transparentColor: GLOBAL_COLORS.transparent.color,
        highlightColor: GLOBAL_COLORS.highlight.color,
        contrastColor: GLOBAL_COLORS.contrast.color,
        glassColor: GLOBAL_COLORS.glass.color
    },
    {
        name: "black-2",
        defaultColor: GLOBAL_COLORS.default.black,
        textPrimaryColor: GLOBAL_COLORS.default.white,
        textSecondaryColor: GLOBAL_COLORS.default.white,
        gradientEndColor: GLOBAL_COLORS.gradientEnd.gray,
        markerDefaultColor: GLOBAL_COLORS.darker.color,
        mutedColor: GLOBAL_COLORS.muted.color,
        lighterColor: GLOBAL_COLORS.lighter.color,
        darkerColor: GLOBAL_COLORS.darker.color,
        darkestColor: GLOBAL_COLORS.darkest.gray,
        transparentColor: GLOBAL_COLORS.transparent.color,
        highlightColor: GLOBAL_COLORS.highlight.color,
        contrastColor: GLOBAL_COLORS.contrast.color,
        glassColor: GLOBAL_COLORS.glass.color
    },
    {
        name: "black-3",
        defaultColor: GLOBAL_COLORS.default.black,
        textPrimaryColor: GLOBAL_COLORS.default.white,
        textSecondaryColor: GLOBAL_COLORS.default.white,
        gradientEndColor: GLOBAL_COLORS.gradientEnd.gray,
        markerDefaultColor: GLOBAL_COLORS.darker.color,
        mutedColor: GLOBAL_COLORS.muted.color,
        lighterColor: GLOBAL_COLORS.lighter.color,
        darkerColor: GLOBAL_COLORS.darker.color,
        darkestColor: GLOBAL_COLORS.default.black,
        transparentColor: GLOBAL_COLORS.transparent.color,
        highlightColor: GLOBAL_COLORS.highlight.color,
        contrastColor: GLOBAL_COLORS.contrast.color,
        glassColor: GLOBAL_COLORS.glass.color
    }
];

export const statusThemes: theme[] = [
    {
        ...defaultTheme,
        name: "permanente",
        defaultColor: GLOBAL_COLORS.default.cyan,
        highlightColor: GLOBAL_COLORS.highlight.cyan,
        glassColor: GLOBAL_COLORS.glass.cyan,
        textPrimaryColor: GLOBAL_COLORS.default.white,
    },
    {
        ...defaultTheme,
        name: "em-progresso",
        defaultColor: GLOBAL_COLORS.default.orange,
        highlightColor: GLOBAL_COLORS.highlight.orange,
        glassColor: GLOBAL_COLORS.glass.orange,
        textPrimaryColor: GLOBAL_COLORS.default.white,
    },
    {
        ...defaultTheme,
        name: "finalizado",
        defaultColor: GLOBAL_COLORS.default.green,
        highlightColor: GLOBAL_COLORS.highlight.green,
        glassColor: GLOBAL_COLORS.glass.green,
        textPrimaryColor: GLOBAL_COLORS.default.white,
    },
    {
        ...defaultTheme,
        name: "incubacao",
        defaultColor: GLOBAL_COLORS.default.purple,
        highlightColor: GLOBAL_COLORS.highlight.purple,
        glassColor: GLOBAL_COLORS.glass.purple,
        textPrimaryColor: GLOBAL_COLORS.default.white,
    },
    {
        ...defaultTheme,
        name: "apodrecido",
        defaultColor: GLOBAL_COLORS.default.gray,
        highlightColor: GLOBAL_COLORS.highlight.gray,
        glassColor: GLOBAL_COLORS.glass.gray,
        textPrimaryColor: GLOBAL_COLORS.default.white,
        mutedColor: GLOBAL_COLORS.muted.gray,
    }
];

export const statusThemeNames = statusThemes
    .map((themeValue: theme) => themeValue.name);
